"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Language =
  | "en"
  | "es"
  | "pt"
  | "ja"
  | "ko"
  | "hi"
  | "de"
  | "fr"
  | "zh";

type TranslationRecord = {
    en: string;
    es: string;
    pt: string;
  ja: string;
  ko: string;
  hi: string;
  de: string;
  fr: string;
  zh: string;
};

interface Translations {
  [key: string]: TranslationRecord;
}

const translations: Translations = {
  title: {
    en: 'Crypto Fear and Greed Index',
    es: 'Índice de Miedo y Codicia Cripto',
    pt: 'Índice de Medo e Ganância Cripto',
    ja: '暗号資産 恐怖と強欲指数',
    ko: '크립토 공포 및 탐욕 지수',
    hi: 'क्रिप्टो भय और लालच सूचकांक',
    de: 'Krypto Angst-und-Gier-Index',
    fr: 'Indice de peur et cupidité crypto',
    zh: '加密恐惧与贪婪指数',
  },
  description: {
    en: 'Crypto Fear and Greed Index is based on volatility, social media sentiments, surveys, market momentum, and more.',
    es: 'El Índice de Miedo y Codicia Cripto se basa en volatilidad, sentimientos en redes sociales, encuestas, momentum del mercado y más.',
    pt: 'O Índice de Medo e Ganância Cripto é baseado em volatilidade, sentimentos de mídia social, pesquisas, momentum de mercado e mais.',
    ja: '暗号資産の恐怖と強欲指数は、ボラティリティ、SNSの感情調査、アンケート、市場モメンタムなどに基づいて算出されます。',
    ko: '크립토 공포 및 탐욕 지수는 변동성, 소셜 미디어 감성, 설문조사, 시장 모멘텀 등을 기반으로 계산됩니다.',
    hi: 'क्रिप्टो भय और लालच सूचकांक अस्थिरता, सोशल मीडिया भावनाओं, सर्वेक्षणों और बाजार गतिशीलता जैसे कई कारकों पर आधारित है।',
    de: 'Der Crypto Angst-und-Gier-Index basiert auf Volatilität, Social-Media-Stimmungen, Umfragen, Markt-Momentum und mehr.',
    fr: "L'indice de peur et cupidité crypto se base sur la volatilité, les sentiments des réseaux sociaux, les sondages, le momentum du marché, etc.",
    zh: '加密恐惧与贪婪指数根据波动性、社交媒体情绪、调查和市场动量等因素计算。',
  },
  marketSentiment: {
    en: 'Market Sentiment',
    es: 'Sentimiento del Mercado',
    pt: 'Sentimento do Mercado',
    ja: '市場センチメント',
    ko: '시장 심리',
    hi: 'बाज़ार भावना',
    de: 'Marktstimmung',
    fr: 'Sentiment du marché',
    zh: '市场情绪',
  },
  now: {
    en: 'Now',
    es: 'Ahora',
    pt: 'Agora',
    ja: '現在',
    ko: '현재',
    hi: 'अभी',
    de: 'Jetzt',
    fr: 'Maintenant',
    zh: '当前',
  },
  yesterday: {
    en: 'Yesterday',
    es: 'Ayer',
    pt: 'Ontem',
    ja: '昨日',
    ko: '어제',
    hi: 'कल',
    de: 'Gestern',
    fr: 'Hier',
    zh: '昨日',
  },
  lastWeek: {
    en: 'Last Week',
    es: 'Última Semana',
    pt: 'Última Semana',
    ja: '先週',
    ko: '지난주',
    hi: 'पिछले सप्ताह',
    de: 'Letzte Woche',
    fr: 'La semaine dernière',
    zh: '上周',
  },
  extremeFear: {
    en: 'Extreme Fear',
    es: 'Miedo Extremo',
    pt: 'Medo Extremo',
    ja: '極端な恐怖',
    ko: '극도의 공포',
    hi: 'अत्यधिक भय',
    de: 'Extreme Angst',
    fr: 'Peur extrême',
    zh: '极度恐惧',
  },
  fear: {
    en: 'Fear',
    es: 'Miedo',
    pt: 'Medo',
    ja: '恐怖',
    ko: '공포',
    hi: 'भय',
    de: 'Angst',
    fr: 'Peur',
    zh: '恐惧',
  },
  neutral: {
    en: 'Neutral',
    es: 'Neutral',
    pt: 'Neutro',
    ja: '中立',
    ko: '중립',
    hi: 'तटस्थ',
    de: 'Neutral',
    fr: 'Neutre',
    zh: '中性',
  },
  greed: {
    en: 'Greed',
    es: 'Codicia',
    pt: 'Ganância',
    ja: '強欲',
    ko: '탐욕',
    hi: 'लालच',
    de: 'Gier',
    fr: 'Cupidité',
    zh: '贪婪',
  },
  extremeGreed: {
    en: 'Extreme Greed',
    es: 'Codicia Extrema',
    pt: 'Ganância Extrema',
    ja: '極端な強欲',
    ko: '극도의 탐욕',
    hi: 'अत्यधिक लालच',
    de: 'Extreme Gier',
    fr: 'Cupidité extrême',
    zh: '极度贪婪',
  },
  chart: {
    en: 'Crypto Fear and Greed Chart',
    es: 'Gráfico de Miedo y Codicia Cripto',
    pt: 'Gráfico de Medo e Ganância Cripto',
    ja: '暗号資産 恐怖と強欲チャート',
    ko: '크립토 공포 및 탐욕 차트',
    hi: 'क्रिप्टो भय और लालच चार्ट',
    de: 'Krypto Angst-und-Gier-Diagramm',
    fr: 'Graphique de peur et cupidité crypto',
    zh: '加密恐惧与贪婪图表',
  },
  download: {
    en: 'Download',
    es: 'Descargar',
    pt: 'Baixar',
    ja: 'ダウンロード',
    ko: '다운로드',
    hi: 'डाउनलोड',
    de: 'Herunterladen',
    fr: 'Télécharger',
    zh: '下载',
  },
  lastUpdated: {
    en: 'Last Updated',
    es: 'Última Actualización',
    pt: 'Última Atualização',
    ja: '最終更新',
    ko: '마지막 업데이트',
    hi: 'अंतिम अद्यतन',
    de: 'Zuletzt aktualisiert',
    fr: 'Dernière mise à jour',
    zh: '最近更新',
  },
  loading: {
    en: 'Loading market sentiment...',
    es: 'Cargando el sentimiento del mercado...',
    pt: 'Carregando o sentimento do mercado...',
    ja: '市場センチメントを読み込み中...',
    ko: '시장 심리를 불러오는 중...',
    hi: 'बाज़ार भावना लोड हो रही है...',
    de: 'Marktstimmung wird geladen...',
    fr: 'Chargement du sentiment du marché...',
    zh: '正在加载市场情绪...',
  },
  fallbackNotice: {
    en: 'Live fear and greed data is currently unavailable. Showing the most recent cached values.',
    es: 'Los datos en vivo del índice de miedo y codicia no están disponibles. Mostrando los valores en caché más recientes.',
    pt: 'Os dados em tempo real do índice de medo e ganância não estão disponíveis. Exibindo os valores em cache mais recentes.',
    ja: 'リアルタイムの恐怖と強欲データは現在利用できません。最新のキャッシュ値を表示しています。',
    ko: '실시간 공포 및 탐욕 데이터가 현재 사용 불가입니다. 가장 최근 캐시 값을 표시합니다.',
    hi: 'वर्तमान में लाइव भय और लालच डेटा उपलब्ध नहीं है। नवीनतम कैश मान दिखाए जा रहे हैं।',
    de: 'Live-Daten für den Angst-und-Gier-Index sind derzeit nicht verfügbar. Es werden die zuletzt zwischengespeicherten Werte angezeigt.',
    fr: "Les données en direct de l'indice de peur et cupidité ne sont pas disponibles. Affichage des dernières valeurs en cache.",
    zh: '实时恐惧与贪婪数据暂不可用。显示最近缓存的数值。',
  },
  fearGreedIndexLabel: {
    en: 'Index',
    es: 'Índice',
    pt: 'Índice',
    ja: '指数',
    ko: '지수',
    hi: 'सूचकांक',
    de: 'Index',
    fr: 'Indice',
    zh: '指数',
  },
  priceLabel: {
    en: 'Price',
    es: 'Precio',
    pt: 'Preço',
    ja: '価格',
    ko: '가격',
    hi: 'कीमत',
    de: 'Preis',
    fr: 'Prix',
    zh: '价格',
  },
  share: {
    en: 'Share',
    es: 'Compartir',
    pt: 'Compartilhar',
    ja: '共有',
    ko: '공유',
    hi: 'साझा करें',
    de: 'Teilen',
    fr: 'Partager',
    zh: '分享',
  },
  shareViaDevice: {
    en: 'Share via device',
    es: 'Compartir desde el dispositivo',
    pt: 'Compartilhar pelo dispositivo',
    ja: 'デバイスで共有',
    ko: '기기에서 공유',
    hi: 'डिवाइस से साझा करें',
    de: 'Über Gerät teilen',
    fr: "Partager via l'appareil",
    zh: '通过设备分享',
  },
  shareOnX: {
    en: 'Share on X (Twitter)',
    es: 'Compartir en X (Twitter)',
    pt: 'Compartilhar no X (Twitter)',
    ja: 'X（Twitter）で共有',
    ko: 'X(트위터)에 공유',
    hi: 'X (Twitter) पर साझा करें',
    de: 'Auf X (Twitter) teilen',
    fr: 'Partager sur X (Twitter)',
    zh: '在 X（Twitter）上分享',
  },
  shareOnLinkedIn: {
    en: 'Share on LinkedIn',
    es: 'Compartir en LinkedIn',
    pt: 'Compartilhar no LinkedIn',
    ja: 'LinkedInで共有',
    ko: 'LinkedIn에 공유',
    hi: 'LinkedIn पर साझा करें',
    de: 'Auf LinkedIn teilen',
    fr: 'Partager sur LinkedIn',
    zh: '在 LinkedIn 上分享',
  },
  copyLink: {
    en: 'Copy link',
    es: 'Copiar enlace',
    pt: 'Copiar link',
    ja: 'リンクをコピー',
    ko: '링크 복사',
    hi: 'लिंक कॉपी करें',
    de: 'Link kopieren',
    fr: 'Copier le lien',
    zh: '复制链接',
  },
  linkCopied: {
    en: 'Link copied!',
    es: '¡Enlace copiado!',
    pt: 'Link copiado!',
    ja: 'リンクをコピーしました！',
    ko: '링크가 복사되었습니다!',
    hi: 'लिंक कॉपी हो गया!',
    de: 'Link kopiert!',
    fr: 'Lien copié !',
    zh: '链接已复制！',
  },
  topCoinsTitle: {
    en: 'Top Cryptocurrencies by Market Cap',
    es: 'Principales criptomonedas por capitalización',
    pt: 'Principais criptomoedas por valor de mercado',
    ja: '時価総額上位の暗号資産',
    ko: '시가총액 상위 암호화폐',
    hi: 'मार्केट कैप के आधार पर शीर्ष क्रिप्टोकरेंसी',
    de: 'Top-Kryptowährungen nach Marktkapitalisierung',
    fr: 'Principales cryptomonnaies par capitalisation',
    zh: '按市值排名的主要加密货币',
  },
  topCoinsSubtitle: {
    en: 'Live prices, daily performance, and 7-day trend data.',
    es: 'Precios en vivo, rendimiento diario y tendencias de 7 días.',
    pt: 'Preços ao vivo, desempenho diário e tendências de 7 dias.',
    ja: 'リアルタイム価格、日次パフォーマンス、7日間のトレンドデータ。',
    ko: '실시간 가격, 일일 성과 및 7일 추세 데이터.',
    hi: 'लाइव कीमतें, दैनिक प्रदर्शन और 7-दिवसीय रुझान डेटा।',
    de: 'Live-Preise, Tagesperformance und 7-Tage-Trends.',
    fr: 'Prix en direct, performances quotidiennes et tendances sur 7 jours.',
    zh: '实时价格、每日表现和7日趋势数据。',
  },
  tableRank: {
    en: 'Rank',
    es: 'Posición',
    pt: 'Posição',
    ja: '順位',
    ko: '순위',
    hi: 'रैंक',
    de: 'Rang',
    fr: 'Classement',
    zh: '排名',
  },
  tableName: {
    en: 'Name',
    es: 'Nombre',
    pt: 'Nome',
    ja: '名称',
    ko: '이름',
    hi: 'नाम',
    de: 'Name',
    fr: 'Nom',
    zh: '名称',
  },
  tablePrice: {
    en: 'Price ({currency})',
    es: 'Precio ({currency})',
    pt: 'Preço ({currency})',
    ja: '価格 ({currency})',
    ko: '가격 ({currency})',
    hi: 'कीमत ({currency})',
    de: 'Preis ({currency})',
    fr: 'Prix ({currency})',
    zh: '价格 ({currency})',
  },
  tableChange1h: {
    en: '1h %',
    es: '1h %',
    pt: '1h %',
    ja: '1時間 %',
    ko: '1시간 %',
    hi: '1घं %',
    de: '1 Std. %',
    fr: '1h %',
    zh: '1小时 %',
  },
  tableChange24h: {
    en: '24h %',
    es: '24h %',
    pt: '24h %',
    ja: '24時間 %',
    ko: '24시간 %',
    hi: '24घं %',
    de: '24 Std. %',
    fr: '24h %',
    zh: '24小时 %',
  },
  tableChange7d: {
    en: '7d %',
    es: '7d %',
    pt: '7d %',
    ja: '7日 %',
    ko: '7일 %',
    hi: '7दिन %',
    de: '7 T. %',
    fr: '7j %',
    zh: '7天 %',
  },
  tableMarketCap: {
    en: 'Market Cap',
    es: 'Capitalización',
    pt: 'Valor de mercado',
    ja: '時価総額',
    ko: '시가총액',
    hi: 'बाज़ार पूंजीकरण',
    de: 'Marktkapitalisierung',
    fr: 'Capitalisation',
    zh: '市值',
  },
  tableVolume24h: {
    en: 'Volume 24h',
    es: 'Volumen 24h',
    pt: 'Volume 24h',
    ja: '24時間出来高',
    ko: '24시간 거래량',
    hi: '24घं वॉल्यूम',
    de: 'Volumen 24h',
    fr: 'Volume 24h',
    zh: '24小时成交量',
  },
  tablePriceGraph: {
    en: 'Price Graph (7D)',
    es: 'Gráfico de precio (7D)',
    pt: 'Gráfico de preço (7D)',
    ja: '価格グラフ (7日)',
    ko: '가격 그래프 (7일)',
    hi: 'मूल्य ग्राफ़ (7दिन)',
    de: 'Preisdiagramm (7T)',
    fr: 'Graphique des prix (7 j)',
    zh: '价格图表（7天）',
  },
  tableLoadError: {
    en: 'Unable to load market data right now.',
    es: 'No se pueden cargar los datos de mercado en este momento.',
    pt: 'Não foi possível carregar os dados de mercado agora.',
    ja: '現在、市場データを読み込めません。',
    ko: '지금은 시장 데이터를 불러올 수 없습니다.',
    hi: 'इस समय बाज़ार डेटा लोड नहीं हो सका।',
    de: 'Marktdaten können derzeit nicht geladen werden.',
    fr: 'Impossible de charger les données de marché pour le moment.',
    zh: '目前无法加载市场数据。',
  },
  paginationPage: {
    en: 'Page {page}',
    es: 'Página {page}',
    pt: 'Página {page}',
    ja: 'ページ {page}',
    ko: '페이지 {page}',
    hi: 'पृष्ठ {page}',
    de: 'Seite {page}',
    fr: 'Page {page}',
    zh: '第 {page} 页',
  },
  paginationOf: {
    en: ' of {total}',
    es: ' de {total}',
    pt: ' de {total}',
    ja: ' / {total}',
    ko: ' / {total}',
    hi: ' में से {total}',
    de: ' von {total}',
    fr: ' sur {total}',
    zh: ' / 共 {total}',
  },
  paginationAssets: {
    en: ' • {count} assets',
    es: ' • {count} activos',
    pt: ' • {count} ativos',
    ja: ' • {count} 資産',
    ko: ' • 자산 {count}개',
    hi: ' • {count} परिसंपत्तियाँ',
    de: ' • {count} Assets',
    fr: ' • {count} actifs',
    zh: ' • {count} 个资产',
  },
  paginationUpdating: {
    en: ' • updating…',
    es: ' • actualizando…',
    pt: ' • atualizando…',
    ja: ' • 更新中…',
    ko: ' • 업데이트 중…',
    hi: ' • अपडेट हो रहा है…',
    de: ' • wird aktualisiert…',
    fr: ' • mise à jour…',
    zh: ' • 更新中…',
  },
  previous: {
    en: 'Previous',
    es: 'Anterior',
    pt: 'Anterior',
    ja: '前へ',
    ko: '이전',
    hi: 'पिछला',
    de: 'Zurück',
    fr: 'Précédent',
    zh: '上一页',
  },
  next: {
    en: 'Next',
    es: 'Siguiente',
    pt: 'Próximo',
    ja: '次へ',
    ko: '다음',
    hi: 'अगला',
    de: 'Weiter',
    fr: 'Suivant',
    zh: '下一页',
  },
  seeMoreCoins: {
    en: 'See More Coins',
    es: 'Ver más monedas',
    pt: 'Ver mais moedas',
    ja: 'さらにコインを見る',
    ko: '더 많은 코인 보기',
    hi: 'अधिक कॉइन्स देखें',
    de: 'Weitere Coins anzeigen',
    fr: 'Voir plus de cryptos',
    zh: '查看更多币种',
  },
  tablePerPageLabel: {
    en: '{count} assets per page',
    es: '{count} activos por página',
    pt: '{count} ativos por página',
    ja: '1ページに {count} 件',
    ko: '페이지당 {count}개 자산',
    hi: '{count} परिसंपत्तियाँ प्रति पेज',
    de: '{count} Assets pro Seite',
    fr: '{count} actifs par page',
    zh: '每页 {count} 个资产',
  },
  coinsPageTitle: {
    en: "Today's Crypto Prices by Market Cap",
    es: 'Precios cripto de hoy por capitalización',
    pt: 'Preços cripto de hoje por valor de mercado',
    ja: '本日の暗号資産価格（時価総額順）',
    ko: '오늘의 암호화폐 시세 (시가총액 기준)',
    hi: 'आज की क्रिप्टो कीमतें (मार्केट कैप के आधार पर)',
    de: 'Heutige Kryptopreise nach Marktkapitalisierung',
    fr: 'Prix des cryptos du jour par capitalisation',
    zh: '今日按市值排列的加密货币价格',
  },
  coinsPageSubtitle: {
    en: 'Track market leaders with live pricing, 24h moves, and sparkline charts powered by CoinStats.',
    es: 'Sigue a los líderes del mercado con precios en vivo, variaciones 24h y gráficas sparkline de CoinStats.',
    pt: 'Acompanhe os líderes do mercado com preços ao vivo, variações em 24h e gráficos sparkline da CoinStats.',
    ja: 'CoinStatsによるリアルタイム価格、24時間の変動、スパークラインチャートで市場の主役を追跡。',
    ko: 'CoinStats의 실시간 가격, 24시간 변동, 스파크라인 차트로 시장 리더를 추적하세요.',
    hi: 'CoinStats द्वारा संचालित लाइव कीमतें, 24 घंटे की चाल और स्पार्कलाइन चार्ट के साथ बाजार के नेताओं को ट्रैक करें।',
    de: 'Verfolge Marktführer mit Live-Preisen, 24h-Bewegungen und Sparkline-Diagrammen von CoinStats.',
    fr: 'Suivez les leaders du marché avec des prix en direct, les variations 24h et des sparklines CoinStats.',
    zh: '通过 CoinStats 提供的实时价格、24 小时涨跌和迷你图表跟踪市场领军者。',
  },
  knowledgeFaqTitle: {
    en: 'Get the Answers to Your Questions',
    es: 'Obtén respuestas a tus preguntas',
    pt: 'Obtenha respostas para suas perguntas',
    ja: '疑問に対する答えを見つけましょう',
    ko: '궁금증에 대한 답을 확인하세요',
    hi: 'अपने प्रश्नों के उत्तर पाएं',
    de: 'Finde Antworten auf deine Fragen',
    fr: 'Obtenez les réponses à vos questions',
    zh: '找到您问题的答案',
  },
  knowledgeFaqSubtitle: {
    en: 'Learn how the Fear & Greed Index works before adding it to your toolkit.',
    es: 'Descubre cómo funciona el índice Fear & Greed antes de usarlo.',
    pt: 'Saiba como o índice Fear & Greed funciona antes de usá-lo.',
    ja: 'Fear & Greed 指数の仕組みを理解してツールキットに加えましょう。',
    ko: '도구로 활용하기 전에 공포-탐욕 지수의 작동 방식을 알아보세요.',
    hi: 'इसे अपनी टूलकिट में जोड़ने से पहले Fear & Greed इंडेक्स कैसे काम करता है जानें।',
    de: 'Erfahre, wie der Fear & Greed Index funktioniert, bevor du ihn nutzt.',
    fr: "Comprenez le fonctionnement de l'indice Fear & Greed avant de l'utiliser.",
    zh: '在使用之前了解恐惧与贪婪指数的运作方式。',
  },
  knowledgeFactorsTitle: {
    en: 'What Does Fear & Greed Index Take Into Account',
    es: 'Qué tiene en cuenta el índice Fear & Greed',
    pt: 'O que o índice Fear & Greed considera',
    ja: 'Fear & Greed 指数の構成要素',
    ko: '공포-탐욕 지수가 고려하는 요소',
    hi: 'Fear & Greed इंडेक्स किन कारकों पर विचार करता है',
    de: 'Was der Fear & Greed Index berücksichtigt',
    fr: "Ce que prend en compte l'indice Fear & Greed",
    zh: '恐惧与贪婪指数考虑哪些因素',
  },
  knowledgeFactorsSubtitle: {
    en: 'Here are the factors that contribute to the index value.',
    es: 'Estos son los factores que contribuyen al valor del índice.',
    pt: 'Veja os fatores que influenciam o valor do índice.',
    ja: '指数を構成する要素をご紹介します。',
    ko: '지수 값을 결정하는 요소들을 살펴보세요.',
    hi: 'यहाँ वे कारक हैं जो इंडेक्स को प्रभावित करते हैं।',
    de: 'Diese Faktoren tragen zum Indexwert bei.',
    fr: 'Voici les facteurs qui composent la valeur de l\'indice.',
    zh: '以下是构成指数值的因素。',
  },
  faq1Title: {
    en: 'What Is Crypto Fear and Greed Index',
    es: 'Qué es el Crypto Fear & Greed Index',
    pt: 'O que é o Crypto Fear & Greed Index',
    ja: '暗号資産 Fear & Greed 指数とは',
    ko: '크립토 공포·탐욕 지수란?',
    hi: 'क्रिप्टो फियर एंड ग्रीड इंडेक्स क्या है',
    de: 'Was ist der Crypto Fear & Greed Index?',
    fr: "Qu'est-ce que le Crypto Fear & Greed Index ?",
    zh: '什么是加密恐惧与贪婪指数？',
  },
  faq1Body1: {
    en: "The ups and downs of the crypto market can be steep, and it's not rare for investors to get discouraged.",
    es: 'Los vaivenes del mercado cripto pueden ser pronunciados y no es raro que los inversores se desanimen.',
    pt: 'Os altos e baixos do mercado cripto podem ser acentuados e não é raro os investidores se desanimarem.',
    ja: '暗号資産市場の上下動は激しく、投資家が動揺するのも珍しくありません。',
    ko: '암호화폐 시장의 등락은 가파르며, 투자자들이 낙담하기 쉽습니다.',
    hi: 'क्रिप्टो बाजार के उतार-चढ़ाव तेज़ हो सकते हैं और निवेशकों का हतोत्साहित होना असामान्य नहीं है।',
    de: 'Die Achterbahnen des Kryptomarkts sind steil und entmutigen viele Anleger:innen.',
    fr: 'Les montagnes russes du marché crypto sont abruptes et peuvent décourager les investisseurs.',
    zh: '加密市场的起伏往往很大，投资者容易感到气馁。',
  },
  faq1Body2: {
    en: 'The index measures the dominant mood on the market so psychological factors are taken into account.',
    es: 'El índice mide el estado de ánimo dominante del mercado, incorporando factores psicológicos.',
    pt: 'O índice mede o humor predominante do mercado, incluindo fatores psicológicos.',
    ja: 'この指数は市場の心理的なムードを測定します。',
    ko: '이 지수는 시장의 지배적인 심리를 측정합니다.',
    hi: 'यह इंडेक्स बाजार के मुख्य मूड को मापता है ताकि मनोवैज्ञानिक पहलुओं को शामिल किया जा सके।',
    de: 'Der Index erfasst die vorherrschende Marktstimmung und berücksichtigt psychologische Faktoren.',
    fr: "L'indice mesure l'humeur dominante du marché et prend en compte les facteurs psychologiques.",
    zh: '该指数衡量市场的主导情绪，将心理因素纳入考虑。',
  },
  faq1Body3: {
    en: 'Knowing where we stand helps avoid common pitfalls and make wiser decisions.',
    es: 'Saber dónde estamos ayuda a evitar errores comunes y tomar mejores decisiones.',
    pt: 'Saber onde estamos ajuda a evitar armadilhas e a tomar decisões melhores.',
    ja: '現在の状況を把握することで、よくある失敗を避け賢明な判断ができます。',
    ko: '현재 상황을 파악하면 흔한 실수를 피하고 현명한 결정을 내릴 수 있습니다.',
    hi: 'यह जानना कि हम कहाँ खड़े हैं, सामान्य गलतियों से बचने और बेहतर निर्णय लेने में मदद करता है।',
    de: 'Zu wissen, wo wir stehen, hilft dabei, typische Fehler zu vermeiden und klügere Entscheidungen zu treffen.',
    fr: 'Savoir où nous en sommes aide à éviter les pièges et à prendre de meilleures décisions.',
    zh: '了解当前所处的位置有助于避免常见陷阱并做出更明智的决策。',
  },
  faq2Title: {
    en: 'How Is Fear & Greed Calculated',
    es: 'Cómo se calcula el Fear & Greed',
    pt: 'Como o Fear & Greed é calculado',
    ja: 'Fear & Greed 指数の算出方法',
    ko: '공포·탐욕 지수는 어떻게 계산되나요?',
    hi: 'Fear & Greed कैसे गणना की जाती है',
    de: 'Wie wird der Fear & Greed Index berechnet?',
    fr: "Comment est calculé le Fear & Greed ?",
    zh: '恐惧与贪婪指数如何计算？',
  },
  faq2Body1: {
    en: 'The index looks at volatility, market performance, social sentiment, and search behaviour.',
    es: 'El índice analiza la volatilidad, el rendimiento del mercado, el sentimiento social y el comportamiento de búsqueda.',
    pt: 'O índice observa volatilidade, desempenho de mercado, sentimento social e buscas.',
    ja: '指数はボラティリティ、市場パフォーマンス、ソーシャル感情、検索動向を分析します。',
    ko: '이 지수는 변동성, 시장 성과, 소셜 감성, 검색 행동을 살펴봅니다.',
    hi: 'यह इंडेक्स अस्थिरता, बाजार प्रदर्शन, सामाजिक भावना और खोज व्यवहार को देखता है।',
    de: 'Der Index untersucht Volatilität, Marktperformance, Social Sentiment und Suchverhalten.',
    fr: "L'indice observe la volatilité, la performance du marché, le sentiment social et les recherches.",
    zh: '该指数考察波动性、市场表现、社交情绪和搜索行为。',
  },
  faq2Body2: {
    en: 'Each data source is weighted to arrive at a single, unified sentiment score.',
    es: 'Cada fuente de datos recibe un peso para obtener un puntaje de sentimiento unificado.',
    pt: 'Cada fonte de dados recebe um peso para chegar a um único placar.',
    ja: 'それぞれのデータソースには重み付けがされ、統一されたスコアに集約されます。',
    ko: '각 데이터 출처에 가중치를 부여하여 하나의 통합 점수를 생성합니다.',
    hi: 'प्रत्येक डेटा स्रोत को एक भार मिलता है ताकि एकीकृत स्कोर प्राप्त हो सके।',
    de: 'Jede Datenquelle wird gewichtet, um zu einem einheitlichen Wert zu gelangen.',
    fr: 'Chaque source de données est pondérée pour produire un score unifié.',
    zh: '对各项数据源进行权重处理后得出统一的情绪得分。',
  },
  faq3Title: {
    en: 'How to Use Fear and Greed Index or What to Use It For',
    es: 'Cómo usar el Fear & Greed Index y para qué sirve',
    pt: 'Como usar o Fear & Greed Index e para que serve',
    ja: 'Fear & Greed 指数の活用方法',
    ko: '공포·탐욕 지수 활용법',
    hi: 'Fear & Greed Index का उपयोग कैसे करें',
    de: 'Wie nutze ich den Fear & Greed Index?',
    fr: "Comment utiliser l'indice Fear & Greed ?",
    zh: '如何使用恐惧与贪婪指数？',
  },
  faq3Body1: {
    en: 'Refer to the index before major decisions to understand when fear or greed may be clouding judgment.',
    es: 'Consúltalo antes de tomar decisiones importantes para entender si el miedo o la codicia están afectando tu juicio.',
    pt: 'Consulte o índice antes de decisões importantes para saber se medo ou ganância estão influenciando seu julgamento.',
    ja: '大きな判断を下す前に指数をチェックし、市場心理の影響を把握しましょう。',
    ko: '중요한 결정을 내리기 전 지수를 참고해 심리가 판단을 흐리고 있는지 살펴보세요.',
    hi: 'महत्वपूर्ण निर्णय लेने से पहले इंडेक्स को देखें ताकि समझ सकें कि डर या लालच आपका निर्णय प्रभावित तो नहीं कर रहा।',
    de: 'Beziehe den Index vor wichtigen Entscheidungen ein, um zu erkennen, wann Emotionen das Urteil trüben.',
    fr: 'Consultez l\'indice avant une décision majeure pour savoir si la peur ou la cupidité brouille votre jugement.',
    zh: '在做重大决策前参考该指数，了解恐惧或贪婪是否影响了判断。',
  },
  faq3Body2: {
    en: 'Fearful periods can uncover undervalued assets, while euphoric markets may call for caution.',
    es: 'En épocas de miedo pueden aparecer activos infravalorados; en mercados eufóricos conviene tener cautela.',
    pt: 'Períodos de medo podem revelar ativos baratos; mercados eufóricos exigem cautela.',
    ja: '恐怖が支配する局面では割安資産が見つかるかもしれません。過熱時は慎重さが求められます。',
    ko: '공포가 커진 시기에는 저평가 자산을, 과열된 장에서는 신중함이 필요합니다.',
    hi: 'डर के समय कम कीमत वाले एसेट मिल सकते हैं, जबकि उत्साह भरे बाजारों में सावधानी जरूरी है।',
    de: 'In Phasen der Angst lassen sich häufig unterbewertete Assets finden, Euphorie verlangt Vorsicht.',
    fr: 'Les périodes de peur révèlent des actifs sous-évalués, les marchés euphoriques appellent à la prudence.',
    zh: '恐惧时期可能出现被低估的资产，而市场亢奋时需要保持谨慎。',
  },
  faq4Title: {
    en: 'How Often Do We Update Crypto Fear and Greed Index',
    es: 'Cada cuánto se actualiza el Crypto Fear & Greed Index',
    pt: 'Com que frequência o índice é atualizado',
    ja: 'Fear & Greed 指数の更新頻度',
    ko: '공포·탐욕 지수는 얼마나 자주 업데이트되나요?',
    hi: 'क्रिप्टो Fear & Greed Index कितनी बार अपडेट होता है',
    de: 'Wie oft wird der Fear & Greed Index aktualisiert?',
    fr: "À quelle fréquence l'indice est-il mis à jour ?",
    zh: '恐惧与贪婪指数多久更新一次？',
  },
  faq4Body1: {
    en: 'The index is refreshed every 12 hours so you always see the latest sentiment reading.',
    es: 'El índice se actualiza cada 12 horas para mostrar siempre el sentimiento más reciente.',
    pt: 'O índice é atualizado a cada 12 horas para mostrar o sentimento mais recente.',
    ja: '指数は12時間ごとに更新され、常に最新のセンチメントが表示されます。',
    ko: '지수는 12시간마다 새로고침되어 최신 심리를 확인할 수 있습니다.',
    hi: 'यह इंडेक्स हर 12 घंटे में अपडेट होता है ताकि आप नवीनतम भावना देख सकें।',
    de: 'Der Index wird alle 12 Stunden aktualisiert, sodass du immer den neuesten Wert siehst.',
    fr: "L'indice est actualisé toutes les 12 heures pour refléter le sentiment le plus récent.",
    zh: '指数每12小时更新一次，确保您看到最新的市场情绪。',
  },
  factor1Title: {
    en: 'Current Volatility',
    es: 'Volatilidad actual',
    pt: 'Volatilidade atual',
    ja: '現在のボラティリティ',
    ko: '현재 변동성',
    hi: 'वर्तमान अस्थिरता',
    de: 'Aktuelle Volatilität',
    fr: 'Volatilité actuelle',
    zh: '当前波动性',
  },
  factor1Body: {
    en: "We compare current volatility to Bitcoin's average over the past 30 and 90 days. Rising volatility increases fear; falling volatility suggests a shift toward greed.",
    es: 'Comparamos la volatilidad actual con la media de Bitcoin en los últimos 30 y 90 días. Más volatilidad supone más miedo; menos volatilidad apunta a más codicia.',
    pt: 'Comparamos a volatilidade atual com a média do Bitcoin nos últimos 30 e 90 dias. Volatilidade alta aumenta o medo; baixa indica tendência à ganância.',
    ja: '現在のボラティリティを過去30日と90日の平均と比較します。高まれば恐怖、低下すれば強欲に傾くとみなします。',
    ko: '현재 변동성을 비트코인의 30일·90일 평균과 비교합니다. 변동성이 오르면 공포가, 낮아지면 탐욕이 확대됩니다.',
    hi: 'हम वर्तमान अस्थिरता की तुलना पिछले 30 और 90 दिनों के बिटकॉइन औसत से करते हैं। बढ़ती अस्थिरता डर बढ़ाती है, घटती अस्थिरता लालच का संकेत देती है।',
    de: 'Wir vergleichen die aktuelle Volatilität mit dem Bitcoin-Durchschnitt der letzten 30 und 90 Tage. Steigende Volatilität erhöht die Angst, sinkende deutet auf Gier hin.',
    fr: 'Nous comparons la volatilité actuelle à la moyenne du Bitcoin sur 30 et 90 jours. Une hausse = peur, une baisse = plus de cupidité.',
    zh: '我们将当前波动率与比特币过去30天和90天的平均值比较。波动率上升意味着恐惧增加，下降则可能转向贪婪。',
  },
  factor2Title: {
    en: 'Momentum/Volume of the Market',
    es: 'Momentum/Volumen del mercado',
    pt: 'Momentum/Volume do mercado',
    ja: '市場のモメンタム／出来高',
    ko: '시장 모멘텀/거래량',
    hi: 'बाज़ार का मोमेंटम/वॉल्यूम',
    de: 'Markt-Momentum/-Volumen',
    fr: 'Momentum/Volume du marché',
    zh: '市场动量 / 交易量',
  },
  factor2Body: {
    en: 'Unusually high buying volume signals greed. We compare current trading activity with 30 and 90 day averages.',
    es: 'Un volumen de compra inusualmente alto indica codicia. Comparamos la actividad actual con los promedios de 30 y 90 días.',
    pt: 'Volume de compra incomum sinaliza ganância. Comparamos a atividade atual com as médias de 30 e 90 dias.',
    ja: '異常な買い需要は強欲を示唆します。現在の取引量を30日・90日平均と比較します。',
    ko: '비정상적으로 높은 매수량은 탐욕을 의미합니다. 현재 거래를 30·90일 평균과 비교합니다.',
    hi: 'असामान्य रूप से ऊँचा खरीद वॉल्यूम लालच का संकेत देता है। हम वर्तमान गतिविधि की तुलना 30 और 90 दिन के औसत से करते हैं।',
    de: 'Ungewöhnlich hohe Kaufvolumina deuten auf Gier hin. Wir vergleichen die Aktivität mit den 30- und 90-Tage-Durchschnitten.',
    fr: "Un volume d'achat inhabituellement élevé signale la cupidité. Nous comparons aux moyennes 30/90 jours.",
    zh: '异常高的买入量意味着更强的贪婪。我们将当前交易与30天和90天均值比较。',
  },
  factor3Title: {
    en: 'Social Media Posts',
    es: 'Publicaciones en redes sociales',
    pt: 'Publicações em mídias sociais',
    ja: 'ソーシャルメディア投稿',
    ko: '소셜 미디어 언급량',
    hi: 'सोशल मीडिया पोस्ट',
    de: 'Social-Media-Beiträge',
    fr: 'Publications sur les réseaux sociaux',
    zh: '社交媒体帖子',
  },
  factor3Body: {
    en: 'We monitor engagement with popular crypto hashtags. Rising interaction means growing greed; falling engagement points to fear.',
    es: 'Monitorizamos la interacción con hashtags cripto. Más interacción implica más codicia; menos apunta a miedo.',
    pt: 'Monitoramos a interação com hashtags cripto. Crescimento = ganância; queda = medo.',
    ja: '人気ハッシュタグへの反応を追跡し、増加なら強欲、減少なら恐怖と捉えます。',
    ko: '인기 해시태그의 참여도를 추적해 증가면 탐욕, 감소면 공포로 해석합니다.',
    hi: 'लोकप्रिय क्रिप्टो हैशटैग पर सहभागिता को ट्रैक करते हैं। बढ़ोतरी लालच और गिरावट डर को दर्शाती है।',
    de: 'Wir verfolgen die Interaktion mit Krypto-Hashtags. Steigende Interaktion = Gier, sinkende = Angst.',
    fr: "Nous suivons l'engagement autour des hashtags crypto. Plus d'engagement = cupidité ; moins = peur.",
    zh: '监控热门加密标签的互动量。互动增加意味着贪婪增长，下降则表明恐惧。',
  },
  factor4Title: {
    en: 'Surveys',
    es: 'Encuestas',
    pt: 'Pesquisas',
    ja: '調査',
    ko: '설문조사',
    hi: 'सर्वेक्षण',
    de: 'Umfragen',
    fr: 'Sondages',
    zh: '调查',
  },
  factor4Body: {
    en: 'Thousands of survey responses each week add direct community sentiment into the score.',
    es: 'Miles de respuestas semanales aportan el sentimiento directo de la comunidad.',
    pt: 'Milhares de respostas semanais adicionam o sentimento direto da comunidade.',
    ja: '毎週集まる多数の回答が、コミュニティの声を指数に反映します。',
    ko: '매주 수천 건의 설문이 커뮤니티의 직접적인 심리를 반영합니다.',
    hi: 'हर सप्ताह हजारों प्रतिक्रियाएँ समुदाय की भावना को सीधे स्कोर में जोड़ती हैं।',
    de: 'Wöchentlich tausende Antworten bringen die Community-Stimmung direkt in die Berechnung ein.',
    fr: 'Des milliers de réponses hebdomadaires injectent le sentiment direct de la communauté.',
    zh: '每周数千份调查答复将社区情绪直接纳入指数。',
  },
  factor5Title: {
    en: 'Bitcoin Dominance',
    es: 'Dominancia de Bitcoin',
    pt: 'Dominância do Bitcoin',
    ja: 'ビットコインのドミナンス',
    ko: '비트코인 점유율',
    hi: 'बिटकॉइन प्रभुत्व',
    de: 'Bitcoin-Dominanz',
    fr: 'Dominance du Bitcoin',
    zh: '比特币主导地位',
  },
  factor5Body: {
    en: 'Growing dominance means investors move back to Bitcoin for safety—a classic fear signal.',
    es: 'Una dominancia creciente refleja un regreso a Bitcoin por seguridad, señal típica de miedo.',
    pt: 'Dominância crescente indica retorno ao Bitcoin por segurança — sinal clássico de medo.',
    ja: 'ドミナンスの上昇は安全資産としてBTCへ回帰しているサインで、恐怖局面を示します。',
    ko: '지배력이 커지면 투자자들이 안전을 위해 비트코인으로 돌아온다는 뜻으로, 공포 신호입니다.',
    hi: 'प्रभुत्व बढ़ना दिखाता है कि निवेशक सुरक्षा के लिए बिटकॉइन पर लौट रहे हैं—यह डर का संकेत है।',
    de: 'Steigende Dominanz signalisiert eine Flucht in Bitcoin zur Sicherheit – ein klassisches Angstsignal.',
    fr: 'Une dominance en hausse montre un retour vers Bitcoin pour la sécurité, un signe de peur.',
    zh: '主导地位上升意味着投资者为了安全回到比特币，这是典型的恐惧信号。',
  },
  factor6Title: {
    en: 'Google Trends',
    es: 'Tendencias de Google',
    pt: 'Google Trends',
    ja: 'Google トレンド',
    ko: '구글 트렌드',
    hi: 'गूगल ट्रेंड्स',
    de: 'Google Trends',
    fr: 'Tendances Google',
    zh: 'Google 趋势',
  },
  factor6Body: {
    en: 'Search queries like "Bitcoin price manipulation" indicate fear, while "How to buy crypto" point toward greed.',
    es: 'Búsquedas como "manipulación precio Bitcoin" indican miedo; "cómo comprar cripto" apuntan a codicia.',
    pt: 'Buscas como "manipulação preço Bitcoin" indicam medo; "como comprar cripto" apontam ganância.',
    ja: '「ビットコイン 価格操作」などの検索は恐怖、「仮想通貨 購入方法」は強欲を示唆します。',
    ko: '"비트코인 가격 조작" 검색은 공포를, "코인 사는 법"은 탐욕을 의미합니다.',
    hi: '"Bitcoin price manipulation" जैसी खोज डर दिखाती हैं जबकि "How to buy crypto" लालच की ओर इशारा करती हैं।',
    de: 'Suchanfragen wie „Bitcoin Preismanipulation" deuten auf Angst, „Wie kaufe ich Krypto" auf Gier.',
    fr: 'Les recherches "Bitcoin price manipulation" montrent la peur ; "How to buy crypto" indique la cupidité.',
    zh: '"比特币价格操纵" 之类的搜索意味着恐惧，而 "如何购买加密货币" 则指向贪婪。',
  },
  footerProduct: {
    en: 'Product',
    es: 'Producto',
    pt: 'Produto',
    ja: 'プロダクト',
    ko: '제품',
    hi: 'उत्पाद',
    de: 'Produkt',
    fr: 'Produit',
    zh: '产品',
  },
  footerResources: {
    en: 'Resources',
    es: 'Recursos',
    pt: 'Recursos',
    ja: 'リソース',
    ko: '자료',
    hi: 'संसाधन',
    de: 'Ressourcen',
    fr: 'Ressources',
    zh: '资源',
  },
  footerOverview: {
    en: 'Overview',
    es: 'Resumen',
    pt: 'Visão geral',
    ja: '概要',
    ko: '개요',
    hi: 'सारांश',
    de: 'Überblick',
    fr: 'Aperçu',
    zh: '概览',
  },
  footerCoins: {
    en: 'Cryptocurrencies',
    es: 'Criptomonedas',
    pt: 'Criptomoedas',
    ja: '暗号資産',
    ko: '암호화폐',
    hi: 'क्रिप्टोकरेंसी',
    de: 'Kryptowährungen',
    fr: 'Cryptomonnaies',
    zh: '加密货币',
  },
  footerBtcDominance: {
    en: 'BTC Dominance',
    es: 'Dominancia BTC',
    pt: 'Dominância BTC',
    ja: 'BTC ドミナンス',
    ko: 'BTC 도미넌스',
    hi: 'BTC प्रभुत्व',
    de: 'BTC-Dominanz',
    fr: 'Dominance BTC',
    zh: 'BTC 主导率',
  },
  footerBtcRainbow: {
    en: 'BTC Rainbow Chart',
    es: 'Gráfico Rainbow BTC',
    pt: 'Gráfico Rainbow BTC',
    ja: 'BTC レインボーチャート',
    ko: 'BTC 레인보우 차트',
    hi: 'BTC रेनबो चार्ट',
    de: 'BTC Rainbow Chart',
    fr: 'Graphique BTC Rainbow',
    zh: 'BTC 彩虹图',
  },
  footerKnowledge: {
    en: 'Knowledge base',
    es: 'Base de conocimiento',
    pt: 'Base de conhecimento',
    ja: 'ナレッジベース',
    ko: '지식 베이스',
    hi: 'ज्ञान आधार',
    de: 'Wissensdatenbank',
    fr: 'Base de connaissances',
    zh: '知识库',
  },
  footerBlog: {
    en: 'Blog',
    es: 'Blog',
    pt: 'Blog',
    ja: 'ブログ',
    ko: '블로그',
    hi: 'ब्लॉग',
    de: 'Blog',
    fr: 'Blog',
    zh: '博客',
  },
  footerSupport: {
    en: 'Contact support',
    es: 'Contactar soporte',
    pt: 'Contato de suporte',
    ja: 'サポートに連絡',
    ko: '지원 문의',
    hi: 'समर्थन से संपर्क करें',
    de: 'Support kontaktieren',
    fr: 'Contacter le support',
    zh: '联系支持',
  },
  footerPrivacy: {
    en: 'Privacy Policy',
    es: 'Política de privacidad',
    pt: 'Política de privacidade',
    ja: 'プライバシーポリシー',
    ko: '개인정보 처리방침',
    hi: 'गोपनीयता नीति',
    de: 'Datenschutz',
    fr: 'Politique de confidentialité',
    zh: '隐私政策',
  },
  footerTerms: {
    en: 'Terms & Conditions',
    es: 'Términos y condiciones',
    pt: 'Termos e condições',
    ja: '利用規約',
    ko: '이용 약관',
    hi: 'नियम व शर्तें',
    de: 'Allgemeine Geschäftsbedingungen',
    fr: 'Termes et conditions',
    zh: '条款与条件',
  },
  footerDisclaimer: {
    en: 'Disclaimer',
    es: 'Descargo de responsabilidad',
    pt: 'Aviso legal',
    ja: '免責事項',
    ko: '면책 조항',
    hi: 'अस्वीकरण',
    de: 'Haftungsausschluss',
    fr: 'Avertissement',
    zh: '免责声明',
  },
  footerAbout: {
    en: 'About Us',
    es: 'Sobre nosotros',
    pt: 'Sobre nós',
    ja: '私たちについて',
    ko: '회사 소개',
    hi: 'हमारे बारे में',
    de: 'Über uns',
    fr: 'À propos de nous',
    zh: '关于我们',
  },
  footerRights: {
    en: 'All rights reserved.',
    es: 'Todos los derechos reservados.',
    pt: 'Todos os direitos reservados.',
    ja: '無断転載を禁じます。',
    ko: '무단 전재를 금합니다.',
    hi: 'सभी अधिकार सुरक्षित।',
    de: 'Alle Rechte vorbehalten.',
    fr: 'Tous droits réservés.',
    zh: '版权所有。',
  },
  navHome: {
    en: 'Home',
    es: 'Inicio',
    pt: 'Início',
    ja: 'ホーム',
    ko: '홈',
    hi: 'होम',
    de: 'Start',
    fr: 'Accueil',
    zh: '首页',
  },
  navCoins: {
    en: 'Cryptocurrencies',
    es: 'Criptomonedas',
    pt: 'Criptomoedas',
    ja: '暗号資産一覧',
    ko: '암호화폐',
    hi: 'क्रिप्टोकरेंसी',
    de: 'Kryptowährungen',
    fr: 'Cryptomonnaies',
    zh: '加密货币',
  },
  btcDominanceLabel: {
    en: 'BTC Dominance',
    es: 'Dominancia BTC',
    pt: 'Dominância BTC',
    ja: 'BTC ドミナンス',
    ko: 'BTC 점유율',
    hi: 'BTC प्रभुत्व',
    de: 'BTC-Dominanz',
    fr: 'Dominance BTC',
    zh: 'BTC 主导占比',
  },
  btcDominanceCurrent: {
    en: 'Current dominance',
    es: 'Dominancia actual',
    pt: 'Dominância atual',
    ja: '現在のドミナンス',
    ko: '현재 도미넌스',
    hi: 'वर्तमान प्रभुत्व',
    de: 'Aktuelle Dominanz',
    fr: 'Dominance actuelle',
    zh: '当前主导率',
  },
  btcDominanceChange: {
    en: '24h change',
    es: 'Cambio 24 h',
    pt: 'Variação 24 h',
    ja: '24時間変化',
    ko: '24시간 변화',
    hi: '24 घंटे का परिवर्तन',
    de: '24h-Veränderung',
    fr: 'Variation 24 h',
    zh: '24小时变动',
  },
  btcDominanceSummaryError: {
    en: 'Unable to load dominance summary.',
    es: 'No se puede cargar el resumen de dominancia.',
    pt: 'Não foi possível carregar o resumo de dominância.',
    ja: 'ドミナンスの概要を読み込めませんでした。',
    ko: '도미넌스 요약을 불러올 수 없습니다.',
    hi: 'प्रभुत्व का सारांश लोड नहीं हो सका।',
    de: 'Dominanz-Übersicht kann derzeit nicht geladen werden.',
    fr: 'Impossible de charger le résumé de la dominance.',
    zh: '无法加载主导率概览。',
  },
  rainbowTitle: {
    en: 'Bitcoin Rainbow Chart',
    es: 'Bitcoin Rainbow Chart',
    pt: 'Bitcoin Rainbow Chart',
    ja: 'Bitcoin Rainbow Chart',
    ko: 'Bitcoin Rainbow Chart',
    hi: 'Bitcoin Rainbow Chart',
    de: 'Bitcoin Rainbow Chart',
    fr: 'Bitcoin Rainbow Chart',
    zh: 'Bitcoin Rainbow Chart',
  },
  rainbowSubtitle: {
    en: "Visualise Bitcoin's historical price in context with sentiment bands.",
    es: "Visualise Bitcoin's historical price in context with sentiment bands.",
    pt: "Visualise Bitcoin's historical price in context with sentiment bands.",
    ja: "Visualise Bitcoin's historical price in context with sentiment bands.",
    ko: "Visualise Bitcoin's historical price in context with sentiment bands.",
    hi: "Visualise Bitcoin's historical price in context with sentiment bands.",
    de: "Visualise Bitcoin's historical price in context with sentiment bands.",
    fr: "Visualise Bitcoin's historical price in context with sentiment bands.",
    zh: "Visualise Bitcoin's historical price in context with sentiment bands.",
  },
  rainbowError: {
    en: 'Unable to load rainbow chart data.',
    es: 'Unable to load rainbow chart data.',
    pt: 'Unable to load rainbow chart data.',
    ja: 'Unable to load rainbow chart data.',
    ko: 'Unable to load rainbow chart data.',
    hi: 'Unable to load rainbow chart data.',
    de: 'Unable to load rainbow chart data.',
    fr: 'Unable to load rainbow chart data.',
    zh: 'Unable to load rainbow chart data.',
  },
  rainbowSelectCoin: {
    en: 'Select coin',
    es: 'Select coin',
    pt: 'Select coin',
    ja: 'Select coin',
    ko: 'Select coin',
    hi: 'Select coin',
    de: 'Select coin',
    fr: 'Select coin',
    zh: 'Select coin',
  },
  rainbowLegendMaximum: {
    en: 'Sell. Seriously, SELL!',
    es: 'Sell. Seriously, SELL!',
    pt: 'Sell. Seriously, SELL!',
    ja: 'Sell. Seriously, SELL!',
    ko: 'Sell. Seriously, SELL!',
    hi: 'Sell. Seriously, SELL!',
    de: 'Sell. Seriously, SELL!',
    fr: 'Sell. Seriously, SELL!',
    zh: 'Sell. Seriously, SELL!',
  },
  rainbowLegendMaximumBubble: {
    en: 'Maximum Bubble Territory',
    es: 'Maximum Bubble Territory',
    pt: 'Maximum Bubble Territory',
    ja: 'Maximum Bubble Territory',
    ko: 'Maximum Bubble Territory',
    hi: 'Maximum Bubble Territory',
    de: 'Maximum Bubble Territory',
    fr: 'Maximum Bubble Territory',
    zh: 'Maximum Bubble Territory',
  },
  rainbowLegendSell: {
    en: 'Sell!',
    es: 'Sell!',
    pt: 'Sell!',
    ja: 'Sell!',
    ko: 'Sell!',
    hi: 'Sell!',
    de: 'Sell!',
    fr: 'Sell!',
    zh: 'Sell!',
  },
  rainbowLegendBubble: {
    en: 'Bubble territory',
    es: 'Bubble territory',
    pt: 'Bubble territory',
    ja: 'Bubble territory',
    ko: 'Bubble territory',
    hi: 'Bubble territory',
    de: 'Bubble territory',
    fr: 'Bubble territory',
    zh: 'Bubble territory',
  },
  rainbowLegendFOMO: {
    en: 'FOMO intensifies',
    es: 'FOMO intensifies',
    pt: 'FOMO intensifies',
    ja: 'FOMO intensifies',
    ko: 'FOMO intensifies',
    hi: 'FOMO intensifies',
    de: 'FOMO intensifies',
    fr: 'FOMO intensifies',
    zh: 'FOMO intensifies',
  },
  rainbowLegendIsItTooLate: {
    en: 'Is this a bubble?',
    es: 'Is this a bubble?',
    pt: 'Is this a bubble?',
    ja: 'Is this a bubble?',
    ko: 'Is this a bubble?',
    hi: 'Is this a bubble?',
    de: 'Is this a bubble?',
    fr: 'Is this a bubble?',
    zh: 'Is this a bubble?',
  },
  rainbowLegendStillCheap: {
    en: 'Still cheap',
    es: 'Still cheap',
    pt: 'Still cheap',
    ja: 'Still cheap',
    ko: 'Still cheap',
    hi: 'Still cheap',
    de: 'Still cheap',
    fr: 'Still cheap',
    zh: 'Still cheap',
  },
  rainbowLegendAccumulate: {
    en: 'Accumulate',
    es: 'Accumulate',
    pt: 'Accumulate',
    ja: 'Accumulate',
    ko: 'Accumulate',
    hi: 'Accumulate',
    de: 'Accumulate',
    fr: 'Accumulate',
    zh: 'Accumulate',
  },
  rainbowLegendBuy: {
    en: 'Buy!',
    es: 'Buy!',
    pt: 'Buy!',
    ja: 'Buy!',
    ko: 'Buy!',
    hi: 'Buy!',
    de: 'Buy!',
    fr: 'Buy!',
    zh: 'Buy!',
  },
  rainbowLegendFireSale: {
    en: 'Fire sale',
    es: 'Fire sale',
    pt: 'Fire sale',
    ja: 'Fire sale',
    ko: 'Fire sale',
    hi: 'Fire sale',
    de: 'Fire sale',
    fr: 'Fire sale',
    zh: 'Fire sale',
  },
  marketOverviewTitle: {
    en: "Today's Market Snapshot",
    es: 'Instantánea del mercado de hoy',
    pt: 'Visão geral do mercado hoje',
    ja: '本日のマーケットスナップショット',
    ko: '오늘의 시장 스냅샷',
    hi: 'आज का बाजार अवलोकन',
    de: 'Heutiger Marktüberblick',
    fr: 'Instantané du marché du jour',
    zh: '今日市场速览',
  },
  marketOverviewSubtitle: {
    en: 'Live global metrics across the entire crypto market.',
    es: 'Métricas globales en vivo de todo el mercado cripto.',
    pt: 'Métricas globais em tempo real de todo o mercado cripto.',
    ja: '暗号資産市場全体のリアルタイム指標。',
    ko: '전 세계 암호화폐 시장의 실시간 지표입니다.',
    hi: 'पूरे क्रिप्टो बाजार की लाइव वैश्विक मीट्रिक्स।',
    de: 'Live-Metriken für den gesamten Kryptomarkt.',
    fr: "Indicateurs mondiaux en direct de l'ensemble du marché crypto.",
    zh: '覆盖整个加密市场的实时全球指标。',
  },
  marketOverviewSummary: {
    en: 'The global crypto market cap is {marketCap}, a {marketCapChange} move over the last 24 hours. 24h trading volume sits around {volume24h}, while Bitcoin dominates about {btcDominance} of the market.',
    es: 'La capitalización global cripto es {marketCap}, un cambio de {marketCapChange} en las últimas 24 horas. El volumen negociado en 24h ronda {volume24h}, y Bitcoin domina aproximadamente {btcDominance} del mercado.',
    pt: 'A capitalização global cripto é de {marketCap}, uma variação de {marketCapChange} nas últimas 24 horas. O volume negociado em 24h está em torno de {volume24h}, enquanto o Bitcoin domina cerca de {btcDominance} do mercado.',
    ja: '世界全体の暗号資産時価総額は {marketCap} で、過去24時間で {marketCapChange} 変動しました。24時間の取引高は約 {volume24h}、ビットコインの市場占有率は約 {btcDominance} です。',
    ko: '전 세계 암호화폐 시가총액은 {marketCap}로 지난 24시간 동안 {marketCapChange} 변동했습니다. 24시간 거래량은 약 {volume24h}, 비트코인 점유율은 약 {btcDominance}입니다.',
    hi: 'वैश्विक क्रिप्टो मार्केट कैप {marketCap} है, जो पिछले 24 घंटों में {marketCapChange} बदला है। 24 घंटे का ट्रेडिंग वॉल्यूम लगभग {volume24h} है, जबकि बिटकॉइन लगभग {btcDominance} बाज़ार पर हावी है।',
    de: 'Die globale Kryptomarktkapitalisierung liegt bei {marketCap}, ein {marketCapChange}-Verlauf in den letzten 24 Stunden. Das 24h-Handelsvolumen beträgt rund {volume24h}, während Bitcoin etwa {btcDominance} des Marktes dominiert.',
    fr: "La capitalisation globale crypto atteint {marketCap}, soit {marketCapChange} sur 24 h. Le volume échangé sur 24 h est d'environ {volume24h}, alors que Bitcoin domine près de {btcDominance} du marché.",
    zh: '全球加密货币总市值为 {marketCap}，较过去24小时变动 {marketCapChange}。24小时交易量约为 {volume24h}，比特币占据约 {btcDominance} 的市场份额。',
  },
  marketOverviewLoading: {
    en: 'Loading global market metrics…',
    es: 'Cargando métricas globales…',
    pt: 'Carregando métricas globais…',
    ja: 'グローバル指標を読み込み中…',
    ko: '글로벌 지표를 불러오는 중…',
    hi: 'वैश्विक मीट्रिक्स लोड हो रही हैं…',
    de: 'Globale Kennzahlen werden geladen…',
    fr: 'Chargement des métriques mondiales…',
    zh: '正在加载全球市场指标…',
  },
  marketOverviewError: {
    en: 'Unable to load global market metrics right now.',
    es: 'No se pueden cargar las métricas globales en este momento.',
    pt: 'Não foi possível carregar as métricas globais agora.',
    ja: '現在、グローバル指標を読み込めません。',
    ko: '현재 글로벌 지표를 불러올 수 없습니다.',
    hi: 'अभी वैश्विक मीट्रिक्स लोड नहीं हो पा रही हैं।',
    de: 'Globale Kennzahlen können derzeit nicht geladen werden.',
    fr: 'Impossible de charger les métriques mondiales pour le moment.',
    zh: '目前无法加载全球市场指标。',
  },
  marketOverviewUpdatedAt: {
    en: 'Last updated {time}',
    es: 'Última actualización {time}',
    pt: 'Atualizado pela última vez {time}',
    ja: '最終更新 {time}',
    ko: '최근 업데이트 {time}',
    hi: 'अंतिम अपडेट {time}',
    de: 'Zuletzt aktualisiert {time}',
    fr: 'Dernière mise à jour {time}',
    zh: '最近更新 {time}',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const saved = window.localStorage.getItem("language") as Language | null;
    if (saved) {
      setLanguage(saved);
    }
  }, []);

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[key];
    if (!translation) return key;
    const base = translation[language] ?? translation.en ?? key;
    if (!params) {
      return base;
    }
    return Object.entries(params).reduce((acc, [paramKey, value]) => {
      const pattern = new RegExp(`{${paramKey}}`, "g");
      return acc.replace(pattern, String(value));
    }, base);
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("language", lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
