import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Crypto Greed Index",
  description:
    "Review the Crypto Greed Index privacy policy to understand how we collect and handle data.",
};

export default function PrivacyPage() {
  return (
    <article className="prose prose-invert max-w-none">
      <h1>Privacy Policy</h1>
      <p>Last updated: March 31, 2025</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use
        and disclosure of Your information when You use the Service and tells You about
        Your privacy rights and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using the
        Service, You agree to the collection and use of information in accordance with
        this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings defined under
        the following conditions. The following definitions shall have the same meaning
        regardless of whether they appear in singular or in plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to access our
          Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is controlled by or is
          under common control with a party, where “control” means ownership of 50% or
          more of the shares, equity interest or other securities entitled to vote for
          election of directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either the “Company”, “We”, “Us” or
          “Our” in this Agreement) refers to cryptogreedindex.com.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile
          device or any other device by a website, containing the details of Your
          browsing history on that website among its many uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Delhi, India.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a
          computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an identified
          or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who
          processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either
          generated by the use of the Service or from the Service infrastructure itself.
        </li>
        <li>
          <strong>Website</strong> refers to cryptogreedindex.com, accessible from{" "}
          <a href="https://www.cryptogreedindex.com">
            https://www.cryptogreedindex.com
          </a>
          .
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is accessing
          or using the Service, as applicable.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You. Personally
        identifiable information may include, but is not limited to Usage Data.
      </p>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device’s Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of our Service
        that You visit, the time and date of Your visit, the time spent on those pages,
        unique device identifiers and other diagnostic data.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track the activity on Our
        Service and store certain information. Tracking technologies used are beacons,
        tags, and scripts to collect and track information and to improve and analyze Our
        Service.
      </p>
      <ul>
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on
          Your Device. You can instruct Your browser to refuse all Cookies or to indicate
          when a Cookie is being sent.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our emails may
          contain small electronic files known as web beacons.
        </li>
      </ul>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>To provide and maintain our Service.</li>
        <li>To manage Your Account.</li>
        <li>For the performance of a contract.</li>
        <li>To contact You.</li>
        <li>To provide You with news and updates.</li>
        <li>To manage Your requests.</li>
        <li>For business transfers.</li>
        <li>For other purposes.</li>
      </ul>

      <h3>Retention of Your Personal Data</h3>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use Your Personal
        Data to the extent necessary to comply with our legal obligations, resolve
        disputes, and enforce our legal agreements and policies.
      </p>

      <h3>Transfer of Your Personal Data</h3>
      <p>
        Your information, including Personal Data, is processed at the Company’s
        operating offices and in any other places where the parties involved in the
        processing are located. It means that this information may be transferred to —
        and maintained on — computers located outside of Your state, province, country or
        other governmental jurisdiction where the data protection laws may differ than
        those from Your jurisdiction.
      </p>

      <h3>Delete Your Personal Data</h3>
      <p>
        You have the right to delete or request that We assist in deleting the Personal
        Data that We have collected about You. Our Service may give You the ability to
        delete certain information about You from within the Service.
      </p>

      <h3>Children’s Privacy</h3>
      <p>
        Our Service does not address anyone under the age of 13. We do not knowingly
        collect personally identifiable information from anyone under the age of 13. If
        You are a parent or guardian and You are aware that Your child has provided Us
        with Personal Data, please contact Us.
      </p>

      <h3>Links to Other Websites</h3>
      <p>
        Our Service may contain links to other websites that are not operated by Us. If
        You click on a third party link, You will be directed to that third party’s site.
        We strongly advise You to review the Privacy Policy of every site You visit.
      </p>

      <h3>Changes to this Privacy Policy</h3>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any
        changes by posting the new Privacy Policy on this page and updating the “Last
        updated” date at the top of this Privacy Policy.
      </p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>
          Email:{" "}
          <a href="mailto:cryptogreedindex@gmail.com">cryptogreedindex@gmail.com</a>
        </li>
        <li>
          Website:{" "}
          <a href="https://www.cryptogreedindex.com/contact">
            https://www.cryptogreedindex.com/contact
          </a>
        </li>
      </ul>
    </article>
  );
}


